# Kommuniker {#kommuniker}
Med pakken *shiny* er det muligt for dig at opbygge og dele interaktive web applikationer direkte fra R.

Du dele dine web applikationer via ShinyApps.io

## Shiny

https://github.com/abhat222/Data-Science--Cheat-Sheet/blob/master/R%20Cheat%20Sheet/shiny-cheatsheet.pdf


## ShinyApps.io
Hvis du skal dele det med mange andre, er der muligt at bruge en cloud løsning – ShinyApps.io

Hvis du vil bruge ShinyApps.io skal følgende være på plads:

•	Du skal også bruge pakken rsconnect
•	Du skal oprette din på ShinyApps.io som brugere
•	Du skal bruge en token fra din konto i din App

ShinyApps.io har flere forskellige løsninger startende ved en gratis til en løsning der koster 299 USD pr. måned.

Den gratis løsning indeholder følgende:

•	5 Applikationer
•	25 Aktive Hosts
•	Support via deres www side
•	Logo fra RStudio i din applikation

## Opret forbindelse
For at publicere din applikation på ShinyApps.io skal du gøre følgende:

1.	Opret og test din løsning lokalt
2.	Klik på knappen Publish to Server
3.	Vælg ShinyApps.io
4.	Du skal kopiere din Token fra ShinyApps.io ind i dette vindow 
Du skal gå ind på konto på ShinyApps.io og vælge:
**Account – Tokens** – Kopier din token – Husk klik på knappen **Show secret** før du kopierer



ShinyApps.io har en rigtig god dokumentation som du kan finde her: https://docs.rstudio.com/shinyapps.io/index.html

